tiktube:
  # proxy config
  # default false
  is-the-proxy-configured: false
  # IP database path
  ip-db-path: D:\\ip2region.xdb
  # enable redis cache, default false
  open-redis: true

server:
  port: 8080
  http2:
    enabled: true
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  web:
    resources:
      chain:
        # enable static resource cache
        cache: true
        enabled: true
        compressed: true
      cache:
        # cache period
        period: 2592000
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    # 192.168.43.128
    url: jdbc:mysql://localhost:3306/tik_tube?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 165423
  servlet:
    multipart:
      enabled: true
      max-file-size: 100000000MB
      max-request-size: 1024000000MB
  data:
    redis:
      host: localhost
      port: 6379
      password:
      # connection timeout
      timeout: 10000
      lettuce:
        pool:
          # max connections
          max-active: 8
          # max wait time (-1 means no limit)
          max-wait: -1
          # max idle connections
          max-idle: 8
          # min idle connections
          min-idle: 0


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl


logging:
  level:
    com:
      buguagaoshu:
        tiktube: debug
  file:
    name: log/spring.log
  logback:
    rollingpolicy:
      max-history: 7